openapi: 3.0.1
info:
  title: Online Order API
  description: A basic API for working with Swagger tools
  version: 1.0.0
servers:
- url: /
paths:
  /orders:
    summary: GET all of the orders data
    description: This path is used to retrieve all of the orders data from the orders.json
      file
    get:
      tags:
      - Orders
      summary: Gets the order data
      description: Retrieve the order information from the orders.ison file
      operationId: get_orders
      responses:
        "200":
          description: OK
          content:
            application/json:
              examples:
                orders:
                  value: |-
                    {"orders":[
                      {
                        "name": "Carey Maynard",
                        "id":"001",
                        "state": "pending"
                      },
                      {
                        "name": "Angela Ayala",
                        "id":"002",
                        "state": "canceled"
                      },
                      {
                        "name": "Regina Yates",
                        "id":"003",
                        "state": "pending"
                      }
                      ]}
        default:
          description: Default error sample response
      x-swagger-router-controller: Orders
  /neworder:
    summary: POST a new order
    description: This path is used to ADD a new order to the orders.json file
    post:
      tags:
      - New Order
      summary: Add a new order
      description: this path uses POST to add a new order to the orders.json file
      operationId: post_orders
      requestBody:
        description: A new order object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: NewOrder
  /update/{id}:
    summary: Change the status of an order
    description: This path is used to change the status of an order matching the provided
      id. It modifies the state attribute of each order.
    put:
      tags:
      - Update Order
      summary: Update the state of an order with matching id
      description: This path uses PUT to update the state of an order with an matching
        in the orders.json file
      operationId: put_orders
      parameters:
      - name: id
        in: path
        description: The id of the order.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: UpdateOrder
  /delete/{id}:
    summary: DELETE an order
    description: This path used to delete an order with a matching id
    delete:
      tags:
      - Delete Order
      summary: Delete an order with matching id
      description: This path DELETE's an order with a matching id from the order.json
        file
      operationId: delete_orders
      parameters:
      - name: id
        in: path
        description: The id of the order.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default error sample response
      x-swagger-router-controller: DeleteOrder
components:
  schemas:
    Order:
      type: object
      properties:
        name:
          type: string
        id:
          type: string
        state:
          type: string
      xml:
        name: Order
